<?php
	require_once('functions/function.php');
	getDashboard_header();
	getDashboard_navbar();
	getDashboard_menufooter();
	getDashboard_topnavigation();
	getDashboard_part('addEmployees.php');
	getDashboard_footer();
?>
